theme: jekyll-theme-minimal
title: "Igor S. Pessi, PhD"
description: "Personal website"
logo: "https://avatars2.githubusercontent.com/u/38423985?s=460&v=4"
show_downloads: "false"
#google_analytics: [Your Google Analytics tracking ID]
