theme: jekyll-theme-minimal
title: "Personal page of Igor S. Pessi"
description: [A short description of your site's purpose]
logo: [Location of the logo]
show_downloads: ["true" or "false" to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]
