title: "Igor S. Pessi, PhD"
description: "Personal website of Igor S. Pessi, PhD"
logo: "https://avatars2.githubusercontent.com/u/38423985?s=460&v=4"
#google_analytics: [Your Google Analytics tracking ID]
